let items = [
    // 100% chance of missing items help
    // items HAVE to have an imageName, name, and description
    // imageName need the image name for both big and small items (ammonia_ampoule needs ammonia_ampoule.png in items, and ammonia_ampoule_big.png in itemsbig), item images are ripped straight from the gamefiles
    // name and description is sourced from both https://discoelysium.fandom.com/wiki/Category:Items and ingame
    // stat is optional and is an array of all stat modifiers
    // every modifier needs type (0:intellect,1:psyche,2:physique,3:motorics,4:nothing,5:political), subtype (name of skill), and amount
    // modifier text is optional but most modifiers have text so treat them as mandatory unless the item doesn't have a modifier description
    // you CAN have the same image for items (like letters and the ledger)
    // no real sorting right now, maybe tags? filter out item type or filter for only item type TODO

    // drugs start //
    { imageName: "ammonia_ampoule", name: "Ampoule of Ammonia", description: "A thin glass tube wrapped in cotton netting, used to treat fainting spells. Produced by Saint-Batiste Pharmaceuticals." },
    { imageName: "nosaphed", name: "Nosaphed", description: "The day nosaphed was invented might go down in history as one of the greater moments of man. Use this to get a faint sense of control in your life. " },
    { imageName: "drouamine", name: "Drouamine", description: "A wide-spread under the counter pain killer. " },
    { imageName: "hypnogamma", name: "Hypnogamma", description: "Hypnogamma! It does wonky things and fixes your brain. " },
    { imageName: "magnesium", name: "Magnesium", description: "Magnesium is the salve upon the wretched torn up by the storm of life." },
    { imageName: "drug_alcohol_commodore_red", name: "Commodore Red", stat: [{ type: 2, subType: "Physique", amount: +1 }, { type: 0, subType: "Morale", amount: -1 }], description: "A large crimson bottle of cheap sugary wine. Made of poverty, sugar, artificial taste enhancers – and a vague memory of grapes. Guaranteed to colour your lips. " },
    { imageName: "drug_alcohol_goracy_brew", name: "Goracy's Brew", stat: [{ type: 2, subType: "Physique", amount: +1 }, { type: 0, subType: "Morale", amount: -1 }], description: "A thermal cup full of hot borscht spiked with high-proof moonshine. Yumm." },
    { imageName: "drug_alcohol_pale_aged_vodka", name: "Pale Aged Vodka", stat: [{ type: 2, subType: "Physique", amount: +1 }, { type: 0, subType: "Morale", amount: -1 }], description: "Vodka, temporarily stored in the pale (or so they say). The crystal clear liquid has been contained in a ship-shaped bottle, commemorating the vanished airship Harnankur. Obliterating your liver has never felt quite so exquisite. " },
    { imageName: "drug_alcohol_potent_pilsner", name: "Potent Pilsner", stat: [{ type: 2, subType: "Physique", amount: +1 }, { type: 0, subType: "Morale", amount: -1 }], description: "A sturdy bottle of beer that tastes like piss. Not that you would know how piss tastes like. Just a guess. The label says it's made in Revachol, by Lafayette Potent Brewery. " },
    { imageName: "drug_pyrholidon", name: "Pyrholidon", stat: [{ type: 1, subType: "Psyche", amount: +1 }, { type: 2, subType: "Health", amount: -1 }], description: "A pretty little puck-shaped cap of purple liquid that can bring on anything from hot flashes to military-grade psychosis. With sufficient tolerance, however, it can make any weather feel balmy – if only for a while. " },
    { imageName: "drug_smokes_astra", name: "Smokes Astra", stat: [{ type: 0, subType: "Intellect", amount: +1 }, { type: 2, subType: "Health", amount: -1 }], description: "These Graad-made cigarettes are remarkable for their high tar content. A favourite of fishermen, police officers and working men the world over." },
    { imageName: "drug_smokes_tioumoutiri", name: "Smokes Tioumoutiri", stat: [{ type: 0, subType: "Intellect", amount: +1 }, { type: 2, subType: "Health", amount: -1 }], description: "These cigarettes smell unusually sweet. Each one is adorned with the silhouette of a boy in a cylindrical cap." },
    { imageName: "drug_speed_bottle", name: "Speed Bottle", stat: [{ type: 0, subType: "Motorics", amount: +1 }, { type: 2, subType: "Morale", amount: -1 }], description: "How convenient! Someone has equipped this tiny bottle of amphetamines with a straw. It's the lorryman's speed on-the-go. " },
    { imageName: "drug_speed_preptide", name: "Speed Saint-Batiste 'PREPTIDE!'", stat: [{ type: 0, subType: "Motorics", amount: +1 }, { type: 2, subType: "Morale", amount: -1 }], description: "This bright orange medicine bottle declares the brand name 'PREPTIDE!' in a sunny, happy manner. Someone has lost the bottle, but who cares! " },
    { imageName: "blue_oblong_pen", name: "Blue Oblong Pen", description: "A blue pen, like a large caliber bullet that shoots out ink, once belonging to Lieutenant Kitsuragi. Comes with a side-order of resentment." },
    { imageName: "kind_green_ape_pen", name: "Kind Green Ape Pen", description: "A pen with a green ape head on one end. The ape has closed its eyes, a kind expression adorning its face. It seems to be meditating. " },
    { imageName: "blue_medicinal_spirit", name: "Blue Medicinal Spirit", description: "The liquid has an unearthly blue tint. The kind that might or might not, but definitely *does* glow in the dark. This is 98,7 pure alcohol. Keep it away from an open flame." },
    { imageName: "spirit_bomb", name: "Spirit Bomb", description: "Your spirit-guide to the party scene, the horrific necktie, is floating serenely in the blue medicinal spirit. As it is still 98.7% alcohol this necktie cocktail is extremely flammable and should be kept far away from an open flame." },
    // drugs end //
    //  books start //
    { imageName: "book_cockatoo", name: "From A to Zrieek! A Guide to Cockatoos", description: "A book about different cockatoo species and their behavioural problems. Perhaps it could also offer some insight into your own often problematic actions? The spectacular Major Majestic cockatoo eyes you from the cover. " },
    { imageName: "book_codex_urik", name: "Codex Urik: the Industrious Dweorgr of Wirrâl", description: "This introductory manual from the Wirrâl setting features an overview of all the basic types of dweorgr. It also describes their social and industrial structures that are mainly based around beards, digging for gold, and alcoholic beverages." },
    { imageName: "book_dick_mullen_and_the_mistaken_identity", name: "Dick Mullen and the Mistaken Identity", description: "Another Dick Mullen book woefully misrepresenting the police work. In this one our detective returns from a trip, having successfully solved a 100-years-old cold case, only to embark on another. Does he finally face the taxing nature of his occupation? No! He doesn't even look like a normal law officer." },
    { imageName: "book_greatest_innossence", name: "The Greatest Innocence", description: "This dusty tome brings knowledge on the history of Innocences. It is written by one João Paolo Salomao Lopez de Fuego, a Mesque fascist, who tries to reach a conclusion on which of the Innocences is the coolest in the world." },
    { imageName: "book_hjelmdallermann", name: "Hjelmdallermann: The Man from Hjelmdall", description: "A classic! On the frontispiece an anatomically unrealistic muscleman is reaching into a mountain stream, yearning to touch his glimmering mirror image. His eyes are full of childlike wonder. On the blood-soaked snow right next to him lie two *giant* zweihänders." },
    { imageName: "book_hjelmdevil", name: "The Man from Hjelmdall and the Devil Woman", description: "The frontispiece of this old paperback features a muscleman in chains, kneeling before a salacious-looking woman on a regal seat. A bonfire lies between the throne and the man, casting shadows on the wall – and the shadow of the vixen's head-dress looks like a pair of demonic horns... " },
    { imageName: "book_la_fumee", name: "La Fumée, Vol. 1 No. 4", description: "The leading intellectual organ of Martinaise communism. Offers a radical Mazovian perspective on a range of contemporary issues. The cover features a stylised portrait of the late King Frissel with a pair of white antlers growing out of his head. " },
    { imageName: "book_medicinal_purposes_of_the_pale", name: "Medicinal Purposes of the Pale", description: "A small green book giving off a peculiar foreboding impression, although it's hard to figure out why. It describes the various ways of healing debilitating ailments through the use of pale, some of which sound implausible at best." },
    { imageName: "book_nilsenism_introduction", name: "A Brief Look at Infra-Materialism", description: "A concise introduction to infra-materialist theory, intended for a general audience. You can tell this particular copy has spent a lot of time in someone's back pocket. " },
    { imageName: "book_primer", name: "A Primer for Small Kids", description: "A textbook for the first grade in primary school. On the cover a humanoid bear is pushing a wheelbarrow full of letters; he's not doing a good job. The letter S is dangerously dangling from the cart, while E fell off a long time ago. Children should pay more attention!" },
    { imageName: "book_sixteen_days_in_coldest_april", name: "Sixteen Days in Coldest April", description: "The cover features a row of concrete buildings with a monochrome rainbow in the sky. It tells a rather excruciating story about two lovers during a period of ethnic unrest in Yugo-Graad. The book has been filed under psychological realism." },
    // books end //
    //  boombox related start //
    { imageName: "boombox", name: "Tape Player Harmon Wowshi W02", description: "This is the reel-to-reel boombox of everyone's youth. A little banged-up, a little chipped, and honestly, not that loud either. Looks cool, though. Excels at being carried on the shoulder, allowing you to play audio tape items and blast music into the face of unsuspecting strangers." },
    { imageName: "music_smallest_church_tape", name: "Tape 'Smallest Church in Saint-Saëns'", description: "The tape you found from a shack on the coast. The A-side has Smallest Church in Saint-Saëns written on it, while the B-side is supposed to contain the instrumental version. Requires a boombox to play." },
    { imageName: "music_whirling_smallest_church", name: "Empty Cassette Case", description: "There used to be a tape in this case, but it was destroyed in a fit of rage. Something about the Etenniers' single Smallest Church in Saint-Saëns must have rubbed someone the wrong way. The label says the song was recorded in '43." },
    { imageName: "tape_lely", name: "Tape 'Doorgunner Megamix'", description: "A magnetic tape acquired from Titus Hardie. It supposedly holds a recording of the mercenary task force radio communications recorded via a de-encryption station. Not a good omen. Requires a boombox to play. " },
    { imageName: "tape_melody_broken", name: "A Bundle of Magnetic Tape", description: "The bronze-coloured tape was found in the branches of hawthorn tree on Rue de Saint-Ghislaine. It gleams whenever a ray of sun hits the surface." },
    { imageName: "tape_melody_fixed", name: "A Reel of Magnetic Tape", description: "The bronze-coloured tape found in the branches of a hawthorn tree has been reconstructed into an usable reel of magnetic tape. It's pretty fragile and in an odd format which doesn't fit into any portable tape players. Nevertheless, Egg Head will be stoked." },
    // boombox related end //
    //  postcards start //
    { imageName: "postcard_coal_city", name: "Postcard Coal City '08", description: "This postcard depicts a forest of smokestacks releasing fat plumes of smoke into blue, cloudless sky. The tinge of age – the colour of old teeth – gives it a sickly look. Written on the back is a single sentence, repeated twice: I got out. I got out. No addressee." },
    { imageName: "postcard_couron", name: "Postcard Couron '33", description: "This one has 'HELL' written on its back. It could not be further from the truth. It's the boom years, and Couron, the nicest district in Revachol West, is enjoying a sun drenched day. Tall and handsome buildings rise from the riverside: steel, iron and yellow limestone, with cloud shadows sliding on the facades. " },
    { imageName: "postcard_grand_couron", name: "Postcard Grand Couron '37", description: "This postcard depicts an ill-advised residential area overlooking the Jamrock Quarter. 13-story buildings line the hillside like sarcophagi, an ominous fog already rising from behind. These are the last boom years -- in '39 the project fails catastrophically, leaving behind an opiate and hepatitis B infested slum. " },
    { imageName: "postcard_la_delta", name: "Postcard La Delta '51", description: "The sunlight has made this postcard almost completely sepia-toned. Midtown traffic passes, overhead the ghosts of skyscrapers disappear into a beige mid-day mist -- vapour rising from the delta on which the district was built. The postcard is pre-paid." },
    { imageName: "postcard_le_jardin", name: "Postcard Le Jardin '21", description: "This laminated post card offers a glimpse across the river. A little more than a decade after the war, the eastern bank is already fully renovated. The hillsides are lush with gardens and residences, someone's parked a small beige airship by the fountain. This postcard will sell for a pretty penny. " },
    { imageName: "postcard_martinaise", name: "Postcard Martinaise '98", description: "A faded picture postcard from the end of the last century shows Martinaise as was before the Revolution. It's the height of summer, Rue de Saint-Ghislaine is teeming with parasol-wielding bourgeoisie and Wild Pines flags buttress the walkway. Nothing is written on the back. " },
    // postcards end //
    //  tools start //
    { imageName: "chaincutters", name: "Chaincutters", description: "The meanest looking pair of cutters you have ever seen, made in Gottwald by Waalshirm Werkzeuge. No chain, wire nor barbed fence will ever stand in your way again. They look hungry, ready to chew steel." },
    { imageName: "flashlight", name: "Flashlight", description: "A police flashlight bearing the logo of Grundstellung RAO. The small dynamo packed inside this hand-held illumination device theoretically gives you the ability to produce a tiny amount of electricity any time anywhere." },
    { imageName: "kvalsund_multitool", name: "Kvalsund KR+2 Multi-Tool", description: "This is an advanced prybar -- a prybar +2, if you will -- built by Kvalsund, in Vaasa. The number of gadgets hidden within the frame of the yellow-and-grey multi-tool will stagger any technician." },
    { imageName: "prybar", name: "Prybar", description: "The red-tipped prybar has Carsson T, Heavy Duty engraved just below the handle. It is satisfyingly heavy -- and perhaps one of the most useful tools to carry around. " },
    // {imageName:"flashlight_2" ,name:"flashlight 2", description:""},
    // tools end //
    //  transcecievers start //
    { imageName: "perfectly_adequate_transceiver", name: "Perfectly Adequate Transceiver", description: "A common radio transceiver, produced by a generic manufacturer. There must be tens of thousands like it all over the world, each one indistinguishable from every other." },
    { imageName: "highly_advanced_transceiver", name: "Highly Advanced Transceiver", description: "An EH-4 multi-modal transceiver, produced by the engineers at Esterhaz Elektronika. Designed for maximum adaptability. In the case of this unit, the frequency dial has been replaced by a key. " },
    { imageName: "highly_expensive_transceiver", name: "Highly Expensive Transceiver", description: "A Kristallsprach Model 9 portable transceiver. Looks (and sounds) expensive. This model includes Kristallsprach's patented 'signal purifier' technology and a bakelite briefcase shell. " },
    // transceviers end //
    //  tare start //
    { imageName: "glass_tare", name: "Glass tare", description: "Empty glass bottle." },
    { imageName: "metal_tare", name: "Metal tare", description: "Empty metal can. " },
    { imageName: "plastic_tare", name: "Plastic tare", description: "Empty plastic bottle. " },
    { imageName: "tare_pile", name: "Tare pile", description: "Your two-way ticket to money town." },
    { imageName: "yellow_plastic_bag", name: "Yellow Plastic Bag Frittte!", description: "This plastic bag has Frittte (sic!) written on it in a dynamic, forceful manner that implies great prices. As you crack it open a malty gust of air flies in your face. Smells of yeast and beer. A perfect place for tare!" },
    // tare end //
    //  photos start // 
    { imageName: "instant_photo_tattoos", name: "Instant Photo of Tattoos", description: "Lieutenant Kitsuragi snapped this photo of the hanged man's tattoos. It displays the intricate web of blue lines stretching across his torso. You have to admit it looks quite cool." },
    { imageName: "rene_photo", name: "Photo of a Happy Couple", description: "A black-and-white photo of a couple posing in front of a ferris wheel. The girl is young and pretty, the man clad in fancy uniform and smiling. On the back a very steady hand has written the words: Revachol Fair, summer of '91. " },
    { imageName: "stock_certificate", name: "Photocopied Stock Certificate", description: "A photocopy of an official certificate that proves the owner holds public shares in Mauer-Koshlai Mercury Group. You don't know how valuable a photocopy of a stock certificate really is, now that you think of it..." },
    // photos end //
    //  guns start //
    { imageName: "armistice_muzzleloader", name: "Kiejl A9 Armistice", description: "A classic 9mm single-shot muzzleloader off the assembly lines of Kiejl Arms. Simple and durable in design, the Kiejl A9 Armistice is one of the most common firearms in the world. Ascetic, frugal, mass-produced. The grip is made from bakelite." },
    { imageName: "gun_ruby", name: "Nachtwey A80 Pepperbox Pistol", description: "This double-barreled pistol is a compact, no-nonsense design, more durable than precise. The walnut-paneled grip is scratched-up, bearing the sheen of long wear in the hands of its previous owner." },
    { imageName: "gun_villiers", name: "Villiers 9mm Pepperbox Pistol", description: "A three-shot revolving barrel Villiers-LaSalle pepperbox, typically assigned to officers of the RCM upon reaching the rank of sergeant. The butt of the gun is worn and the engraving on the side reads: Sunrise, Parabellum! This is *your gun*, no doubt about it." },
    { imageName: "deserter_gun", name: "Triangong 4-46", description: "The bolt-action 4.46 caliber Triangong is the poor-man's sniper rifle. While not the most reliable of firearms, it is relatively precise due to a very manageable recoil, thus allowing the shooter to take multiple consequitive shots fast. Triangongs were provided to the Commune of Revachol as military aid from the Hsin-Yao Commune in Safre. The Belle-Magraves taken from the loyalists were unreliable bad rifles, while the Triangong was reliably bad, making them superior for most purposes. This particular piece is missing a scope, though. " },
    { imageName: "antique_rifle", name: "Antique Belle-Magrave Rifle", description: "A broken Belle-Magrave BM446 from ages past. It's a four-shot, bolt-action military rifle with a wooden frame. It misses a bolt-spring and the mechanism is jammed shut." },
    { imageName: "deserter_scope", name: "T-9/32 Rifle Scope", description: "A common 30mm sniper scope attachable to almost any bolt-action 4.46 caliber. It uses an older-style non-dotted rangefinding reticle. Seaweed is still stuck on the lens and it's suffered water damage from its time in the phasmid's dowry." },
    { imageName: "bullet", name: "9mm bullet", description: "A 9mm bullet – the world's most popular and widely used cartridge. The low cost and wide availability contributes to the caliber's continuing popularity." },
    { imageName: "bullets", name: "9mm rounds", description: "A handful of 9mm rounds -- the world's most popular and widely used cartridges. The low cost and wide availability contributes to the caliber's continuing popularity." },
    { imageName: "fractured_bullet", name: "Fractured Bullet", description: "The bullet mushroomed out on impact. It now looks more like a fanciful jacket button than something that could pierce skin, flesh, and bone." },
    // guns end //
    //  misc start //
    { imageName: "game_suzerainty", name: "Board game Suzerainty", description: "A civilization-building board game where you get to choose a nation and set off to colonise and exploit other cultures. A star-shaped note on the box proclaims the game now includes a completely new Genocide option." },
    { imageName: "game_wirral", name: "Board game Wirrâl", description: "A high-pasternal fantastique populaire board game, illustrated with bucolic vistas and featuring odd-looking humanoid creatures. It's the 3rd edition mega-setting supplements module and can't be played without the main game." },
    { imageName: "figurine_set_headless_faln_rider", name: "Figurine Set Headless FALN Rider", description: "The plastic Headless FALN Rider sits atop his equally plastic bull, his posture indicating either desperation or pride. Comes as a set with the infamous FALN cap for which he lost his head. (The head is not included.)" },
    { imageName: "figurine_set_revolutionary", name: "Figurine Set Revolutionary", description: "What a nice little figurine! A turn-of-the-century leftist revolutionary in ragged clothes. On his head lies a lopsided hat, seemingly an ushanka. In his hand he carries a little musket." },
    { imageName: "cindys_brush", name: "Cindy's Brush", description: "A paintbrush belonging to Cindy the Skull, an aspiring artist. Its bristles smell nauseatingly of heavy fuel oil. Specks of red, orange, and green paint cover the aluminium ferrule." },
    { imageName: "cindys_painting", name: "Cindy's Chef D'oeuvre", description: "It's the painting that Cindy sold to you. The canvas is a fragment of plastic snapped off some larger object that's been coated thick with emulsion. A blitz of dotty colours shoot out from one of the corners." },
    { imageName: "deluxe_topping_pie", name: "Deluxe Topping Pie", description: "This huge topping pie from The Future of Food Topping Pie Company is wheat-free, vegan, and possibly still warm. Biting into it, you may taste any or all of the following: meatless bacon, avocado, figs, basil, pineapple, lime, pepper, and paprika." },
    { imageName: "ham_sandwich", name: "Giant Ham Sandwich", description: "This might be the biggest sandwich you have ever seen. The size is almost intimidating, invoking feelings of inadequacy. Abundant in components, rich in both smell and taste (probably), this truly is the work of a master craftsman." },
    { imageName: "gum_wrapper", name: "Apricot Chewing Gum Wrapper ", description: "A gleaming chewing gum wrapper found in the pocket of the labourer jeans. It gives off an ever-so-faint scent of apricots... Your mouth starts watering." },
    { imageName: "cents_40", name: "40 centims", description: "A small collection of metal coins on the table." },
    { imageName: "Money", name: "Money", description: "Fiscal resources in the amount of... Whatever you find.  " },
    { imageName: "dockworker_id_card", name: "Dockworker Shift Card", description: "A standard issue dockworker shift card, doubling as a worker's permit. The bottom left corner holds a picture of the man this item used to belong to. The two of you look nothing alike – just so you'd know." },
    { imageName: "badge", name: "RCM Badge LTN-2JFR DU BOIS", description: "Thick blue piece of acryllic, covering a thin leaf of paper with the officer's name and rank on it. Next to the writing you see a man stare back at you -- a younger version of *you*, already disintegrating inside, but still presentable on the outside. " },
    { imageName: "klaasje_passport", name: "(Evidence) Klaasje's Passport", description: "This well travelled passport, with visas stamped in it, is issued by the Republic of Oranje. You found it in the phasmid's nest on the island. You can open it for more details. " },
    { imageName: "library_card", name: "Folded Library Card", description: "A library card found from a pocket of the dead man on the Martinaise boardwalk. It's still slightly damp to the touch. The cover bears the stamp of Jamrock Public Library." },
    { imageName: "box_with_locusts", name: "Box with Locusts", description: "A cardboard box with several rows of' little holes in the lid. Though at first glance the box seems perfectly ordinary, upon closer examination, it's obvious that it has been prepared with great care." },
    { imageName: "fuel_canister_lum", name: "LUM Fuel Canister", description: "There is still some fuel in this battered canister. A litre or two. The metal looks decades old, the logo of the automotive manufacturer LUM has faded on the side. " },
    { imageName: "fuel_canister_rcm", name: "Banged-Up Fuel Canister", description: "A dented stainless steel canister for transporting and storing heavy fuel oil. A logo on its side has been partially stripped over years of use. The government-issued red-dyed fuel oil inside looks like paint -- though it smells much, much worse." },
    { imageName: "filament_memory_off_site_copy", name: "Off-Site Copy Filament Memory", description: "The cube-like crisscross of filaments feels oddly fragile in your hand, its intricate structure still cold to the touch. Silver tape on the side reads: OFF-SITE COPY. NOTE! This filament contains information that can be read using a radiocomputer.  " },
    { imageName: "filament_memory_production_schedule", name: "Production Schedule Filament Memory", description: "The cube-like crisscross of filaments feels oddly fragile in your hand, its intricate structure covered in dust. Silver tape on the side reads: PRODUCTION SCHEDULE. NOTE! This filament contains information that can be read using a radiocomputer. " },
    { imageName: "key_ring", name: "Whirling-in-Rags Keyring", description: "It says Whirling-In-Rags on the aluminum keyring. It collects all keys you've found. NOTE! Hovering over the Keys slot on the left lists all keys that have been equipped to the keyring." },
    { imageName: "commemorative_pin", name: "Commemorative Pin", description: "This unusually tasteful pin was produced to celebrate the Saint-Batiste Summer Dinghy Races '31. It has the warm glow of a well-loved memento." },
    { imageName: "dried_may_bells", name: "Dried May Bells", description: "This is the wildflower you caught – one of a bouquet of muguets that you found on the Whirling roof. It's shedding its petals quickly in your pocket." },
    { imageName: "radiant_spinners", name: "Radiant Spinners", description: "The magnificent hubcap spinners that Lieutenant Kitsuragi has donated to you so that you can pay for your room at the Whirling. They are slate blue and shimmer haughtily in the light. Kim confiscated them from a Coalition official's son, who was interrupting traffic while driving under the influence. " },
    { imageName: "lieutenants_handkerchief", name: "Lieutenant's Handkerchief", description: "The handkerchief given to you by Lieutenant Kitsuragi. One corner is adorned with lace and a tiny embroidered 'Portier'." },
    { imageName: "lieutenants_notebook", name: "Lieutenant's Notebook", description: "Lieutenant Kitsuragi's notebook, a Mnemotechnique A6 – classic. You can't help wondering why you don't have one yourself. " },
    { imageName: "rubys_journal", name: "Ruby's Journal", description: "A well-loved journal with a brown leather cover and the brand name 'SCHNELLER' embossed on the back. It seems to have served as a loyal friend to a lonely traveller." },
    { imageName: "map_of_martinaise", name: "Map of Martinaise", description: "A worn and torn map of the Martinaise area, dating from '48. A title on the top reads: Bienvenue à Revachol. It's a bit out of date, as it was originally created by a design studio in a failed attempt to spruce up Martinaise and turn it into a fancy tourist location. " },
    { imageName: "ruffed_grouse_taxidermy", name: "Ruffed Grouse Taxidermy", description: "The dead body of a grouse stuffed with some unknown material. From a distance it might just pass off as the real thing. The bird itself looks extremely... ruffled. And slightly grumpy. " },
    { imageName: "sabre", name: "Standart 115mm Sabre", description: "The blade of this mass-produced sabre has dulled over the years and won't slice or stab anyone. It still commands respect in your hand, however. Holding on to its bakelite hilt fills you with a sense of purpose – and a memory of the date." },
    { imageName: "samaran_speakers", name: "Speakers from the People's Republic of Samara", description: "Why did you even buy those? These are no magic speakers. These are lame speakers. All they will ever produce is a faint memory of the song you're trying to listen to. Sell them for cash." },
    { imageName: "note_from_fridge", name: "Handwritten Note from the Fridge", description: "A handwritten note you found from the giant ice bear fridge. It still bears some marks from the fruit-shaped kitchen magnets that were used to secure it to the refrigerator door. " },
    { imageName: "novelty_cheque", name: "Giant Novelty Cheque", description: "This 20x50cm cheque looks like it's meant to be handed over ceremoniously on a gala-like event. It supposedly exchanges for 25 reál at your local Frittte store. Below the number, a careful hand has written the words: Cuntstable's rent. All of it. NOTE! Worthless in a pawnshop.    " },
    { imageName: "shotput_ball", name: "Shotput Ball", description: "A ball used for playing shotput. You feel like you should hold on to this and make good use of it. To sell such beautiful, old school sports equipment would be a sin. " },
    { imageName: "white_envelope", name: "White Envelope", description: "A white envelope with a stamp attached to the upper-right corner, handed to you by Evrart Claire. Inside are some legal documents with two names printed on them: Isobel Sadie and Lilienne Carter. Both signatures are required. " },
    { imageName: "yellow_man_mug", name: "Yellow-Man Mug", description: "This broken-eared mug somehow made its way into the Whirling-in-Rags dumpster. It depicts a person of Samaran descent frolicking in a field of saffron flowers, buck-toothed and grinning feeble-mindedly. It seems to be a cheap knockoff of some colonial-era antique. " },
    { imageName: "ledger_damaged", name: "Damaged Ledger", description: "This is the ledger you found in the trash. It's full of notes written in a man's dense cursive. Have a closer look -- maybe it can be salvaged to start keeping notes on the case?" },
    { imageName: "ledger_of_failure_and_hatred", name: "Ledger of Failure and Hatred", stat: [{ type: 1, subType: "Empathy", amount: +1, text: "Got fucked" }, { type: 1, subType: "Inland Empire", amount: +1, text: "The unwell feeling" }, { type: 1, subType: "Authority", amount: -2, text: "Got fucked real bad" }], description: "This is the same ledger you found in the trash, only *worse* somehow. It makes you think about the letter. About the woman's handwriting. About not wanting to get out of bed in the morning. " },
    { imageName: "ledger_of_failure_and_hatred", name: "Ledger of Oblivion", stat: [{ type: 1, subType: "Authority", amount: +1, text: "Threw that shit away" }, { type: 1, subType: "Suggestion", amount: +1, text: "Mentally healthy power-move" }, { type: 1, subType: "Inland Empire", amount: -1, text: "Don't even care" }], description: "This is the ledger you found in the trash. It emits oblivion. A thin veneer of la-la-la, what I don't know can not hurt me covers its pages. You look at it and it makes you feel surprisingly solid, actually." },
    // misc end //
    //  glasses start //
    { imageName: "glasses_bugeyes", name: "Oversized Superstar Sunglasses", stat: [{ type: 3, subType: "Savoir Faire", amount: +1, text: "Dazzling reflexes" }, { type: 0, subType: "Visual Calculus", amount: -1, text: "The mirror lies" }], description: "Is your own stardom too dazzling for your eyes? Can't bear to look at your own fabulous reflection in the mirror? Then these classic oversized sunglasses are for you. " },
    { imageName: "glasses_flipup", name: "Flip-up Glasses The Auditor", stat: [{ type: 0, subType: "Logic", amount: +1, text: "Balancing the books" }, { type: 1, subType: "Authority", amount: -1, text: "Filthy boho, probably a narcomaniac" }], description: "These flip-up sunglasses were fashionable in the Old, but have since lost their popularity. Their thin gold-alloy wire frames are a reminder of drug-addled bohemian artists. These days the glasses are only favored by organized crime accountants who desire to look cool." },
    { imageName: "glasses_rect", name: "Neat Office Shades", stat: [{ type: 3, subType: "Visual Calculus", amount: +1, text: "Eye of the reckoner" }, { type: 0, subType: "Drama", amount: -1, text: "A bit dry" }], description: "These were stuffed away in the Dockworker's Union office. They're perfect for scribbling down paperwork when the sun tries to get in your eye. Good for staring down suspects too." },
    { imageName: "glasses_self_destruction", name: "Shades of Self-Destruction", stat: [{ type: 2, subType: "Electrochemistry", amount: +1, text: "Wreck it, Jack" }, { type: 0, subType: "Logic", amount: -1, text: "Suicidal ideations" }], description: "These death-tinted shades come with an odd longing for self-destruction. They're ugly -- you don't even need a mirror to know this. Describing them is futile; better get a glass of wine." },
    // glasses end //
    //  gloves start //
    { imageName: "gloves_bum", name: "Fingerless Gloves", stat: [{ type: 2, subType: "Electrochemistry", amount: +1, text: "Cigarette-stained fingertips" }], description: "Gasoline-stained fingerless gloves in navy blue. They've been worn threadbare, but, being made of wool, still provide some warmth and comfort." },
    { imageName: "gloves_faln", name: "FALN Ultra Series Gloves", stat: [{ type: 2, subType: "Half Light", amount: +1, text: "Unfiltered contact" }], description: "For ultimate performance efficiency these FALN Ultra series gloves come fingerless and with a grippy padding covering the palms, making these ideal for quadrupedal movement – or for lifting cargo." },
    { imageName: "gloves_garden", name: "Yellow Gardening Gloves", stat: [{ type: 3, subType: "Interfacing", amount: +1, text: "Bye-bye, bugs!" }], description: "Thick latex gardening gloves in classic canary yellow. Maybe you should retire, take up gardening as a hobby? It's worth a thought. " },
    { imageName: "gloves_t500", name: "Fairweather T-500 Gauntlets", stat: [{ type: 3, subType: "Intefacing", amount: +2, text: "Strength in digits" }], description: "Clenching and unclenching your fist has never been so fun -- the tiny ceramic plates make a lovely clicking sound when your fingers move. The gloves are a bit sandy, but the grip is phenomenal." },
    // gloves end //
    //  hat start //
    { imageName: "hat_amphibian_sports_visor", name: "Amphibian Sports Visor", stat: [{ type: 3, subType: "Perception", amount: +1, text: "Beady suspicious eyes" }], description: "The malformed green frog of the visor seems to keep an eye on your surroundings. A beady suspicious eye. The lime-tinted cellophane appears to be poorly molded -- the imprint says Made in Safre. " },
    { imageName: "hat_bum", name: "Orange Bum Hat", stat: [{ type: 3, subType: "Reaction Speed", amount: +1, text: "Feeling twitchy" }, { type: 0, subType: "Rhetoric", amount: -1, text: "Bum brain" }], description: "An orange beanie with a couple of big-ass holes on the side. It looks like it might have been used as a mask during an armed robbery." },
    { imageName: "hat_camionneur", name: "Camionneur Cap", stat: [{ type: 3, subType: "Hand/Eye Coordination", amount: +1 }], description: "With its long visor and mesh back, this cap keeps the sun out of your eyes and lets perspiration waft away. Might be more useful in the summer though." },
    { imageName: "hat_faln", name: "FALN Pipo Pipo", stat: [{ type: 0, subType: "Logic", amount: +2, text: "Ultimate peak focus" }, { type: 3, subType: "Perception", amount: -1, text: "Eyes on the road" }], description: "The small wire framing inside this futuristic-looking FALN pipo-hat gives it the aerodynamic shape of a swoop-skiers helmet, but none of its protective qualities. Covers the wearer's ears and eyebrows to bring down the drag coefficient." },
    { imageName: "hat_headset", name: "Specialist-Grade Headset", stat: [{ type: 0, subType: "Inland Empire", amount: +2, text: "In your own head." }, { type: 3, subType: "Reaction Speed", amount: -1, text: `"Say that again?"` }], description: "A giant pair of cans to keep you safe from the world. This particular set seems to have changed hands several times. May become sweaty after extended use." },
    { imageName: "hat_mullen", name: "Dick Mullen's Hat", stat: [{ type: 0, subType: "Encyclopedia", amount: +1, text: "Book-smart" }], description: "If anything, this wide-rimmed hat looks even *better* than the hat Dick Mullen wears. Dick Mullen is stupid -- and not even real. You're real. Your brain is real. Your real real brain is inside the hat." },
    { imageName: "hat_rcm", name: "RCM Lieutenant's Cap", stat: [{ type: 1, subType: "Authority", amount: +1, text: "Member of an organization" }], description: "The cap is sturdy and comfortable, and seems to retain its form very well. It fits you perfectly. The inside of it smells... like cheap tobacco and typewriter ink. It feels familiar somehow. Perhaps it, too, is yours? Though how *the pigs* got it is a mystery." },
    { imageName: "hat_revolutionary", name: "Revolutionary's Hat", stat: [{ type: 5, subType: "Mazovian Socio-Economics", amount: +1, text: "Friendly neighbourhood communard" }], description: "An *ushanka* with the mazovian logo -- a pair of deer antlers -- on its silvery-white front. Your ears feel cuddled and cared for by the state." },
    { imageName: "hat_samaran", name: "Samaran Conical Hat", stat: [{ type: 0, subType: "Logic", amount: +1, text: "Super logical for a cop to wear this" }, { type: 1, subType: "Suggestion", amount: -1, text: "Insensitive bachelor party vibes" }], description: "This tawny cone-shaped hat looks like a beacon of Samaran wisdom, its straws sticking up like antennas. Thank god you can't really see people's reactions when they see you strolling around in this incredibly insensitive headpiece." },
    { imageName: "hat_t500", name: "Fairweather T-500 Helmet", stat: [{ type: 2, subType: "Half-Light", amount: +1, text: "Head as battering ram" }, { type: 1, subType: "Suggestion", amount: -1, text: "A fighter, not a lover" }], description: "This monstrous looking, bug-eyed ceramic helmet was in the phasmid's nest. It still has some reeds sticking out of it -- and it smells of seawater -- but it's otherwise wearable, if not exactly comfortable. Putting it on feels scary somehow..." },
    // hat end //
    //  neck start // 
    { imageName: "neck_scented_scarf", name: "Scented Scarf", stat: [{ type: 2, subType: "Shivers", amount: +1, text: "Springtime cold" }, { type: 2, subType: "Physical Instrument", amount: -2, text: "Allergies" }], description: "This light springtime scarf smells like men's cologne mixed with cheap laundry detergent. Someone must have left it behind, probably from a date? Wear it if you want to delude yourself that spring has arrived." },
    { imageName: "neck_setting_sun_medal", name: "Medal The Setting Sun", stat: [{ type: 0, subType: "Rhethoric", amount: +1, text: "The heroic deeds (of others)" }], description: "A deep blue star sits inside a radiant orange sun. Vaillance, the word most often used to describe exceptional valor in combat, is written underneath. Medals like this aren't bought, they are earned." },
    { imageName: "neck_teratorn_tie", name: "Eight-Eyed Teratorn Tie", stat: [{ type: 1, subType: "Inland Empire", amount: +1, text: "Octuple vision" }, { type: 2, subType: "Volition", amount: +1, text: "Cryptid's protection" }], description: "A slender bolo tie held together by an antique clasp in the shape of a bird skull. The skull features eight cavities for eyes. It's disturbing, but you can't look away. " },
    { imageName: "neck_tie", name: "Horrific Necktie", stat: [{ type: 1, subType: "Inland Empire", amount: +1, text: "Vivid imagination" }], description: "The necktie is adorned with a garish pattern. It's disturbingly vivid. Somehow you feel as if it would be wrong to ever take it off. It's your friend now. You will betray it if you change it for some boring scarf. " },
    { imageName: "neck_winter_scarf", name: "Army Surplus Winter Scarf", stat: [{ type: 1, subType: "Empathy", amount: +2, text: "Plight of the underclass" }, { type: 3, subType: "Composure", amount: -1, text: "Sucks to be poor" }], description: "This towy old scarf itches when wrapped around the neck. It has *humanitarian aid* written all over it. Yet you know that thousands all over the isola are suffering the same fate as you -- the fate of uncomfortable army surplus scarves." },
    { imageName: "neck_winter_scarf_red", name: "Mesque Banger's Silk Scarf", stat: [{ type: 2, subType: "Pain Threshold", amount: +1, text: "Bangers don't cry" }], description: "This huge red scarf is still dusty from lying in the church. A subtle red-on-red embroidery embellishes it with cocky roosters and Mesque floral motives." },
    // neck end //
    //  jacket start // 
    { imageName: "missing_jacket_filthy", name: "Filthy Jacket", description: "This filthy rag has been at the mercy of the elements for quite some time. It's streaked with seagull shit and abnormally stiff from god-knows-what natural processes. You can't even tell what brand it is. " },
    { imageName: "jacket_faln", name: "FALN Faln Windbreaker", stat: [{ type: 2, subType: "Half-Light", amount: +1, text: "Always hot" }, { type: 2, subType: "Pain Threshold", amount: +1, text: "Element-proof" }], description: "This windbreaker is like a protective cocoon, placing the wearer's torso into a pocket universe where wind, water, dirt and fire cannot harm them. Huge writing 100% synthetic is proudly displayed on the chest. It lets absolutely no air through. (Warning: Item not actually fire-proof.)" },
    { imageName: "jacket_fritte_raincoat", name: "FRITTTE Plastic Rain Coat", stat: [{ type: 3, subType: "Endurance", amount: +1, text: "Part of Frittte's army" }], description: "A transparent plastic rain coat with FRITTTE (sic!) written on the back. The package photo shows a group of happy Revacholians dancing in the rain. " },
    { imageName: "jacket_fucktheworld", name: "Leather Jacket Fuck the World", stat: [{ type: 2, subType: "Half-Light", amount: +1, text: "Darkening world" }, { type: 0, subType: "Rhetoric", amount: -1, text: "Inelegant statement" }], description: "A leather jacket that quite recently belonged to a hoodlum who understood love for what it really is. It has the hoodlum's *nom de guerre* written on the back. It's quite a statement." },
    { imageName: "jacket_pissflaubert", name: "Leather Jacket Pissf****t", stat: [{ type: 0, subType: "Drama", amount: +1, text: "No fucks given" }, { type: 1, subType: "Authority", amount: -1, text: "Wait, I'm a detective?!" }], description: "A leather jacket that quite recently belonged to a young man who possessed some intimate knowledge on the human condition. It has his *nom de guerre* written on the back. It's quite a statement." },
    { imageName: "jacket_interisolar", name: "Interisolary Suit Jacket", stat: [{ type: 1, subType: "Suggestion", amount: +1, text: "Dressed for the occasion" }], description: "A muted brown suit jacket perfect for a day at the office or an evening at a cafe. The red rose at the bottom of the left breast pocket is slowly wilting. " },
    { imageName: "jacket_interisolar_white", name: "Saramirizian Lounge Jacket", stat: [{ type: 0, subType: "Conceptualization", amount: +1, text: "Summer plans" }], description: "A classic white summer jacket, loved both by the Saramirizian Communist Party and the accompanying subtropical drug traffickers. It fits you well – regardless of your political ambitions. " },
    { imageName: "jacket_kimono_robe", name: "Party Dragon's Silk Robe", stat: [{ type: 0, subType: "Drama", amount: +1, text: "Become the dragon" }, { type: 2, subType: "Electrochemistry", amount: +1, text: "Become an addict... in a strange bathing robe" }], description: "This sleazy-silky bathing robe in vibrant blues features a roaring dragon on its front, ready to take off into the night. A red belt has been provided for fastening. It's culturally insensitive, but only for people who are not from Seol. The real Seolites probably don't care. " },
    { imageName: "jacket_korovjev", name: "Korojev Jacket", stat: [{ type: 0, subType: "Logic", amount: +1, text: "Checkmate" }], description: "This swanky checkered jacket flatters your form in a way that makes you feel the *fun* kind of serious. It has really nice, roomy pockets, too." },
    { imageName: "jacket_mullen", name: "Pinball Maker's Coat", stat: [{ type: 1, subType: "Empathy", amount: +1, text: "M. Nyflox blues" }, { type: 3, subType: "Hand/Eye Coordination", amount: +1 }], description: "This dusty old coat used to belong to someone called 'M. Nyflox'. The name is stitched into the silk lining. It smells of moths and ancient engine grease, but fits you perfectly. A strange, lonely emotion fills you when you tighten the belt around your waist." },
    { imageName: "jacket_nansencoat", name: "Polar Anorak", stat: [{ type: 3, subType: "Composure", amount: +1, text: "Under the polar lights" }, { type: 2, subType: "Shivers", amount: +1, text: "Gift from La Revacholiere" }], description: "Layers and layers of polyvinyl and artificial sheepskin make this coat ideal for traversing snowy plains on dog sledges. Somehow you knew it would be waiting for you underground, in a sunken pipe. And you found it. It's as if the city gifted it to you, to keep you safe." },
    { imageName: "jacket_navalcoat", name: "Signal-Blue Naval Coat", stat: [{ type: 1, subType: "Suggestion", amount: +1, text: "Aye, Captain!" }, { type: 2, subType: "Half-Light", amount: -1, text: "Officerial poise" }], description: "This classic double-breasted coat suits everyone -- including you. And if you ever find yourself battling winds at the helm of a ship then the coat's heavy fabric has got your back... even if moths have left a few holes in it. " },
    { imageName: "jacket_patrol_cloak", name: "RCM Patrol Cloak", stat: [{ type: 1, subType: "Esprit de Corps", amount: +1, text: "Taking back the streets" }, { type: 2, subType: "Shivers", amount: +1, text: "Know thy neighbourhood" }], description: "A police cloak made from heavy tarpaulin. It would be nigh wind- and waterproof if there weren't three bullet holes scattered on the surface. The signature white rectangle of the RCM covers the garment's back." },
    { imageName: "jacket_rcm", name: "RCM Commander's Jacket", stat: [{ type: 1, subType: "Esprit de Corps", amount: +1, text: "United in black" }, { type: 0, subType: "Visual Calculus", amount: +1, text: "Sharp eye" }], description: "A black uniform jacket with RCM's signature white rectangle on its right sleeve and backside. Letters inside the collar read: LTN-2JFR. The jacket is of exceptional quality, other than some minor wear-and-tear." },
    { imageName: "jacket_reflective_vest", name: "Reflective Construction Vest", stat: [{ type: 2, subType: "Endurance", amount: +1, text: "Safety first" }, { type: 3, subType: "Reaction Speed", amount: -1, text: "Impossible to miss" }], description: "A ludicrously reflective safety vest like those favoured by construction and road repair crews. Comes with a replaceable battery back. Makes you feel like a deep sea anemone." },
    { imageName: "jacket_suede", name: "Disco-Ass Blazer", stat: [{ type: 1, subType: "Esprit de Corps", amount: +1, text: "Halogen watermarks" }], description: "Looks like someone skinned this blazer off some long extinct disco-animal. It has an enigmatic white rectangle on the back and the right sleeve." },
    { imageName: "jacket_windbreaker_surf", name: "Dynamic Winderbreaker Surf", stat: [{ type: 3, subType: "Composure", amount: +1, text: "Keep your cool" }, { type: 2, subType: "Shivers", amount: -1, text: "Weatherproof" }], description: "This nylon windcheater is so dynamic; it wraps around you like a membrane. Equipped with a stowable hood, the backside of the garment is covered in sport- and summer-related text. It swishes softly as you walk." },
    // jacket end //
    //  shirt start // 
    { imageName: "shirt_dress_disco", name: "White Satin Shirt", stat: [{ type: 0, subType: "Conceptualization", amount: +1, text: "A real *statement* to wear" }, { type: 1, subType: "Suggestion", amount: -1, text: "Unsavory odour" }], description: "This white satin shirt used to be fancy. It used to really *catch the light*. Now it smells like someone took a piss in the armpits. " },
    { imageName: "shirt_faln", name: "FALN Arrower Shirt", stat: [{ type: 1, subType: "Hand/Eye Coordination", amount: +1, text: "Sleeveless aim" }], description: "This FALN training shirt has seen one wash too many. It retains its unusual design -- one sleeve short, the other long -- but little of its original colours. A giant 'F' swooshes across its chest, now in grey. " },
    { imageName: "shirt_hjelmdall", name: "T-Shirt 'Man From Hjelmdall'", stat: [{ type: 2, subType: "Physical Instrument", amount: +1, text: "Inspiring musculature" }, { type: 2, subType: "Shivers", amount: +1, text: "Sprawling saga" }, { type: 1, subType: "Authority", amount: -2, text: "Too old for the shirt" }], description: "The Man from Hjelmdall is standing in front of a burning village, dual-wielding his ever-present zweihänders. His muscles look ready to burst out of the two-dimensional print and into your three-dimensional life." },
    { imageName: "shirt_interisolar", name: "Interisolary Dress Shirt", stat: [{ type: 0, subType: "Logic", amount: +1, text: "Good with numbers" }], description: "Pressed and spotless gleaming white shirt. The kind that serious men wear -- at serious interisolary offices. (Not yet piss-soaked or cum-stained.)" },
    { imageName: "shirt_mesh", name: "Insane Mesh Tank Top ", stat: [{ type: 0, subType: "Drama", amount: +1, text: "Clinically insane" }], description: "plaWhere did you even get that one? No, really, who put it in that drawer?! No further comments. Wear it at your own risk.ceholdar" },
    { imageName: "shirt_polo", name: "White Polo Shirt", stat: [{ type: 0, subType: "Rhetoric", amount: +1, text: "What's polo anyway?" }, { type: 1, subType: "Empathy", amount: -1, text: "No, really. what the hell is polo?" }], description: "This shirt looks worn and smells a bit. You can't help but wonder -- who would leave it stuffed in a tare container? What kind of man would even *wear* a polo shirt? This might be one of life's mysteries that will never be solved... " },
    { imageName: "shirt_t500", name: "Fairweather T-500 Cuirass", stat: [{ type: 2, subType: "Pain Threshold", amount: +1, text: "Thicker skin" }, { type: 1, subType: "Volition", amount: +1, text: "Borrowed confidence" }, { type: 1, subType: "Empathy", amount: -1, text: "Mania of invulnerability" }], description: "This vitreous enamel cuirass fits snugly and redistributes kinetic energy across its countless white plates. Amazingly, it fits under your coat! And it also makes pretty porcelain sounds when shaken. " },
    { imageName: "shirt_tank_top", name: "White Tank Top", stat: [{ type: 1, subType: "Physical Instrument", amount: +1, text: "Work it!" }], description: "Tank top! Gym vest! Reeking of sweat! This sleeveless shirt is the best choice if you're not afraid to show off your masculine upper body and that hairy chest." },
    // shirt end //
    //  pants start // 
    { imageName: "pants_bellbottom", name: "Flare-cut Trousers", stat: [{ type: 2, subType: "Electrochemistry", amount: +1, text: "Tight around the crotch" }, { type: 3, subType: "Savoir Faire", amount: -1, text: "Tight around the thighs" }], description: "These golden brown trousers are flare-cut. Normal bell-bottom trousers would be boot-cut, but these are far from normal. They are someone's piss-soaked, cum-stained party pants. " },
    { imageName: "pants_faln", name: "FALN Modular Track Pants", stat: [{ type: 3, subType: "Savoir Faire", amount: +1, text: "Spacious crotch / liquid fit" }, { type: 2, subType: "Physical Instrument", amount: +1, text: "Performance-unlimited" }], description: "Entry level FALN Modular track pants, meant to get the urban athele started down the FALN-path. Labels say Hydrophobic 100%, SymanTec, and FALN Mirova Lab, creating an air of pseudoscientific mystery around these pants. They feel rubbery and futuristic to touch. " },
    { imageName: "pants_interisolar", name: "Interisolary Trousers", stat: [{ type: 5, subType: "Kingdom of Conscience", amount: +1 }], description: "Tailored trousers in light brown, moderate in every aspect. They're absolutely unremarkable -- in other words, *perfect*." },
    { imageName: "pants_interisolar_white", name: "Saramirizian Lounge Trousers", stat: [{ type: 5, subType: "Kingdom of Conscience", amount: +1 }, { type: 0, subType: "Visual Calculus", amount: +2, text: "Spotless mind" }], description: "White, the colour of bold people. Especially if you're going to be traversing through the muddy streets of Martinaise. Goes well with a white jacket.   " },
    { imageName: "pants_itchy_angry", name: "Itchy Pants", stat: [{ type: 2, subType: "Half-Light", amount: +2, text: "Itch-rage" }, { type: 3, subType: "Composure", amount: -1, text: "Bees in your pants" }, { type: 3, subType: "Savoir Faire", amount: -1, text: "Really uncomfortable" }], description: "Itchy pants. These pants make you angry. Good LORD these pants are UNCOMFORTABLE. Punch someone in the face! They are striped and calf-length; too tight around thighs, too loose around waist -- the worst case scenario." },
    { imageName: "pants_jeans", name: "Pour L'Homme Labourer Jeans", stat: [{ type: 2, subType: "Electrochemistry", amount: +1, text: "God-Ass" }, { type: 3, subType: "Reaction Speed", amount: -1, text: "Hindsighted" }], description: "Although these jeans look worn, the wearer must have had an ass given to them by the mighty Lord himself. That beautiful peach-shaped man-ass has imprinted itself so deep in the fabric you can't but wonder if wearing them would start molding your own vague rearside into a more *shapely* form as well. " },
    { imageName: "pants_jeans_black", name: "Regular Black Jeans", stat: [{ type: 3, subType: "Composure", amount: -1, text: "A normal day for a normal guy" }], description: "Thank god for black jeans. Everyone looks good in black jeans. Combine it with your favourite book t-shirt and a yellow plastic bag to channel that laidback 'trash bin raccoon meets a cool professor' vibe. Or do whatever you want -- it's just a pair of black jeans after all." },
    { imageName: "pants_jeans_red", name: "Mesque Banger's Red Jeans", stat: [{ type: 2, subType: "Physical Instrument", amount: +1, text: "Hell-rooster" }], description: "These rowdy red jeans feature an embroidered rooster at the bottom of the left leg, indicating a Mesque origin. A crest of flowers surrounds the bird." },
    { imageName: "pants_rcm", name: "RCM Lieutenant's Pants", stat: [{ type: 1, subType: "Authority", amount: +1, text: "Walking tall" }, { type: 1, subType: "Suggestion", amount: +1, text: "Seems to know what he's doing" }], description: "These cotton-blend pants are very comfortable, yet manage to look official and businesslike. Inside, someone's delicate hand has embroidered a signature on the garment's care label: it says Perseus Black." },
    // pants end //
    //  shoes start // 
    { imageName: "hanged_boots_raw", name: "Fairweather T-500 Boots with Rotting Flesh", description: "Don't smell these boots. Better yet, don't even *think* about them – unless it's to think about how you're going to get them clean, that is. For now, they're unsellable, unwearable, and just downright disgusting." },
    { imageName: "shoes_cavalry", name: "Franconigerian Cavalry Boots", stat: [{ type: 3, subType: "Perception", amount: +1, text: "A view from above" }], description: "Good old calf-length cavalry boots. Mount that horse and ride into the night! The heel comes in handy, too -- it definitely makes you some good five centimetres taller, but could it be that it's also making you *sharper*, more perceptive to your surroundings, now that you've gained a new perspective? " },
    { imageName: "shoes_donks", name: "Speedfreaks DONKS", stat: [{ type: 2, subType: "Physical Instrument", amount: +1, text: "HEAVY-FOOTED" }, { type: 2, subType: "Electrochemistry", amount: +1, text: "HARD STEPPIN'" }, { type: 3, subType: "Interfacing", amount: -1, text: "TOTALLY UNSAFE FOR DRIVING" }], description: "OFFICIAL MERCHANDISE OF R-R-R-REVACHOL'S HOTTEST STATION, SPEEDFREAKS FM. LIGHT-UP, STEEL-TOED SNEAKERS TO K-K-K-KEEP YOU DRIVING FAST AND FLASHY." },
    { imageName: "shoes_faln", name: "FALN Ultra Series Sneakers", stat: [{ type: 3, subType: "Hand/Eye Coordination", amount: +1 }, { type: 3, subType: "Reaction Speed", amount: +1, text: "Limitless grip" }, { type: 0, subType: "Encyclopedia", amount: -1, text: "Too fast for facts" }], description: "The Ultra Series FALN sneakers put lightness and grip above all else. With grip-tape covered SpringBoard soles and ultralight synth-fabric technology you can exit every corner with the maximum traction of a gentleman's racer." },
    { imageName: "shoes_fancy_loafer", name: "Black Monkstraps", stat: [{ type: 5, subType: "Indirect Modes of Taxation", amount: +1, text: "Affluent money-maker man" }], description: "These Per & Ingersoll shoes have no lacing, but a strap and a buckle. Due to their elegant and affluent design they have been described as the 'most advanced' dress shoe. So advanced, in fact, that walking through slush and mud does not leave a single trace on them.   " },
    { imageName: "shoes_fancy_loafer_brown", name: "Brown Derbies", stat: [{ type: 5, subType: "Indirect Modes of Taxation", amount: +1 }, { type: 3, subType: "Perception", amount: +1, text: "Not thinking about your shoes" }], description: "What's the opposite of green snakeskin shoes? That's right, a pair of brown derbies. Wear them if you don't want to think about your feet. " },
    { imageName: "shoes_snakeskin", name: "Green Snakeskin Shoes", stat: [{ type: 3, subType: "Composure", amount: +1, text: "Awesome watchtower heels" }, { type: 3, subType: "Savoir Faire", amount: -1, text: "Heels ridiculously high" }], description: "They may have lost some of their lustre over the years, but these green crocodile leather shoes fit you perfectly." },
    { imageName: "shoes_snakeskin_left", name: "Green Shoe (Left Foot)", description: "This green crocodile leather shoe has a high heel and chrome embellishments. It fits your left foot perfectly. Now all that remains is to find the *other* shoe. " },
    { imageName: "shoes_snakeskin_right", name: "Green Shoe (Right Foot)", description: "This green crocodile leather shoe is exclusively for the right foot -- yours. Pick out the shards of glass and it fits you perfectly." },
    { imageName: "shoes_snakeskin_red", name: "Mesque Banger's Red Brogues", stat: [{ type: 1, subType: "Empathy", amount: +1, text: "In someone else's shoes" }], description: "These dapper snakeskin shoes have an almost invisible white-on-white flower motive sewn on the tongue. The toe caps are still dusty from lying in the church. " },
    { imageName: "shoes_t500", name: "Fairweather T-500 Greaves", stat: [{ type: 1, subType: "Authority", amount: +2, text: "Put your foot down" }, { type: 3, subType: "Composure", amount: -1, text: "Shoes too big to fill" }], description: "These greaves are light as feathers – and just a tad too big for you, but don't let that bother you. With these on, you look like some kind of future-warrior! *And* they'll keep you safe if you accidentally shoot yourself in the foot. So worth it. " },
    // shoes end //
    //  dice start // 
    { imageName: "wirral_die", name: "Standard Wirrâl Die", description: "This basic 24-sided role-playing die can be used to get results for several dice. It's made of East-Semenese Snakewood and embellished with plant motives. It reminds you of plain- and hill-welkins. " },
    { imageName: "red_police_die", name: "Icosahedral Red Die", description: "This 20-sided die is made of bloodstone and inlaid with lapis lazuli, its colours resembling police sirens. Its blue partner is missing. Kinda looks like... the fire department arriving on the scene? Got fucked. Shitfingers. " },
    { imageName: "police_dice", name: "Icosahedral Dice Set Sirens", description: "These two 20-sided dice have the colours of a police alarm -- bloodstone for red and lapis lazuli for blue. If you roll them and squint your eyes it looks like you're arriving on the scene. And it's raining." },
    { imageName: "anti_wirral_die", name: "Standard Anti-Wirrâl Die", description: "This standard 24-sided role-playing die can be used to get results for several dice. It's made of alligator jawbone cast in acrylic resin and embellished with frost motives. Looks like a minuscule blizzard is stuck in there. " },
    { imageName: "superstar_dice", name: "The Magnetic Dice Set", description: "These 100-sided dice are made of ivory and inlaid with magnetic lodestone. When rolled together, pips on the dice interact with each other by pulling and pushing -- just like magnetic personalities." },
    { imageName: "sorry_die", name: "Amber Die With a Mosquito", description: "This unusual 13-sided die is made of amber. A fossilized mosquito has been trapped inside, legs bent beneath the weight of eternal rest. " },
    { imageName: "apocalypse_die", name: "Cursed Iilmaraan Die", description: "This spherical die with an octahedral cavity and a small internal weight will settle with one of the 6 phrases facing up: take all, lose all, 50/50, nothing happens, and pale. It's made of bog oak burl, coloring it malevolent black." },
    // dice end //
    //  
]   
const loadItemNumber = 25;
let numItemLoaded = 0;
let currentId = -1;
const grid = document.getElementById("grid-display");
const bigImage = document.getElementById("big-image");
const bigName = document.getElementById("big-name");
const bigDesc = document.getElementById("big-description");
const gridButton = document.getElementById("loadButton");
const gridButtonfast = document.getElementById("loadButtonFast");
const gridButtoncontainer = document.getElementById("loadButtoncontainer");
const icon = document.getElementById("linkIcon");
const statMods = document.getElementById("stat-modifiers");

// wait to load initial items before loading in page
document.addEventListener('DOMContentLoaded', (event) => {
    //the event occurred
    loadGrid(items);
    // items.forEach((element, index) => {
    //     grid.insertAdjacentHTML("beforeend" , `<img src="./Items/${element.imageName}.png" class="grid-item" onclick="loadItem(${index})">`);
    // });
    loadItem(Math.floor(Math.random() * 25));
})


function loadGrid(array, startNum = 0, amount = 25) {
    for (let i = startNum; i < amount + startNum; i++) {
        const element = array[i];
        if (!(numItemLoaded >= array.length)) {
            gridButtoncontainer.insertAdjacentHTML("beforebegin", `<img src="./Items/${element.imageName}.png" alt="${element.name}" class="grid-item" onclick="loadItem(${i})" tabindex="0" role="button" title="${element.name}">`)
        }
        numItemLoaded++;
    }
}

// load big item image and other elements to the right side 
function loadItem(id) {
    // dont reload if already loaded
    if (currentId != id) {
        currentId = id;
        let element = items[id];
        bigImage.alt = element.name;
        bigName.innerText = element.name;
        bigDesc.innerText = element.description;
        bigImage.src = `./Items/${element.imageName}.png`;
        loadBigImage(`./ItemsBig/${element.imageName}_big.png`);
        icon.setAttribute('href', `./Items/${element.imageName}.png`);
        document.title = `DE Item List | ${element.name}`;
        statMods.innerHTML = "";
        if (element.stat != undefined) {
            element.stat.forEach(e => {
                statMods.style.display = "block";
                statMods.innerHTML += `<p class="stat">${(e.amount >= 0) ? "+" : "-"}${Math.abs(e.amount)} <b class="statName stat${e.type}">${e.subType}</b>${(e.text != undefined) ? ": " + e.text : ""}</p>`;
            });
        } else {
            statMods.style.display = "none";
        }
    }
}


// teehee
async function loadBigImage(imageUrl) {
    let img;
    let placeholderImg = bigImage.src;
    const imageLoadPromise = new Promise(resolve => {
        img = new Image();
        img.onload = resolve;
        img.src = imageUrl;
    });

    await imageLoadPromise;
    // if placeholder image changed while waiting to load don't change image 
    if (bigImage.src == placeholderImg) {
        bigImage.src = imageUrl;
    }
    return img;
}

// load 25 items
gridButton.addEventListener('click', () => {
    loadGrid(items, numItemLoaded, loadItemNumber);
    if (numItemLoaded >= items.length) {    
        gridButton.style.display = "none";
        gridButtoncontainer.style.display = "none";
        gridButton.style.display = "none";
    }
})
// load all items
gridButtonfast.addEventListener('click', () => {
    loadGrid(items, numItemLoaded, (items.length - numItemLoaded));
    gridButton.style.display = "none";
    gridButtoncontainer.style.display = "none";
    gridButton.style.display = "none";
})